In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

kidney1516= pd.read_sas('KIQ_U_I.XPT')
#kidney1516= pd.read_sas('KIQ_U_I.XPT')

In [2]:
kidney=kidney1516[['SEQN','KIQ022']]

In [3]:
kidney.loc[(kidney.KIQ022==2),"KIQ022"]=0
kidney.loc[(kidney.KIQ022==9),"KIQ022"]=0

/Users/Christy/anaconda3/envs/289/lib/python3.7/site-packages/pandas/core/indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
/Users/Christy/anaconda3/envs/289/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/Christy/anaconda3/envs/289/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [4]:
kidney

         SEQN  KIQ022
0     83732.0     0.0
1     83733.0     0.0
2     83734.0     1.0
3     83735.0     0.0
4     83736.0     0.0
5     83737.0     0.0
6     83741.0     0.0
7     83742.0     0.0
8     83744.0     0.0
9     83747.0     0.0
10    83750.0     0.0
11    83752.0     0.0
12    83754.0     0.0
13    83755.0     0.0
14    83757.0     0.0
15    83758.0     0.0
16    83761.0     0.0
17    83762.0     0.0
18    83767.0     0.0
19    83769.0     0.0
20    83773.0     0.0
21    83775.0     0.0
22    83776.0     0.0
23    83777.0     0.0
24    83781.0     0.0
25    83784.0     0.0
26    83785.0     0.0
27    83786.0     0.0
28    83787.0     0.0
29    83788.0     0.0
...       ...     ...
5689  93651.0     0.0
5690  93652.0     0.0
5691  93653.0     0.0
5692  93654.0     0.0
5693  93655.0     0.0
5694  93656.0     0.0
5695  93659.0     0.0
5696  93661.0     0.0
5697  93663.0     0.0
5698  93664.0     0.0
5699  93665.0     0.0
5700  93668.0     1.0
5701  93670.0     0.0
5702  93671.0     0.0
5703  93672.0     0.0
5704  93675.0     0.0
5705  93676.0     0.0
5706  93677.0     0.0
5707  93679.0     1.0
5708  93682.0     0.0
5709  93684.0     0.0
5710  93685.0     0.0
5711  93689.0     0.0
5712  93690.0     0.0
5713  93691.0     0.0
5714  93695.0     0.0
5715  93696.0     0.0
5716  93697.0     0.0
5717  93700.0     0.0
5718  93702.0     0.0

[5719 rows x 2 columns]

In [5]:
#kidney_weak
kidney.to_csv('kidney_weak1516.csv',index=False)