In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

plasma_glucose1314= pd.read_sas('GLU_H.XPT')
plasma_glucose1516= pd.read_sas('GLU_I.XPT')

In [2]:
plasma1=plasma_glucose1314[['SEQN','LBXGLU']]
plasma2=plasma_glucose1516[['SEQN','LBXGLU']]

In [3]:
plasma1=plasma1.dropna()
plasma2=plasma2.dropna()

In [4]:
#plasma=plasma['LBXGLU']

In [5]:
plasma1.loc[(plasma1.LBXGLU<=126),"LBXGLU"]=0
plasma2.loc[(plasma2.LBXGLU<=126),"LBXGLU"]=0

In [6]:
plasma1.loc[(plasma1.LBXGLU>126),"LBXGLU"]=1
plasma2.loc[(plasma2.LBXGLU>126),"LBXGLU"]=1

In [7]:
plasma1

         SEQN  LBXGLU
0     73559.0     1.0
1     73561.0     0.0
2     73564.0     0.0
3     73568.0     0.0
4     73574.0     0.0
5     73576.0     0.0
6     73577.0     0.0
8     73580.0     0.0
9     73581.0     0.0
10    73587.0     0.0
11    73596.0     0.0
13    73598.0     0.0
14    73600.0     1.0
15    73607.0     0.0
16    73610.0     0.0
17    73618.0     0.0
18    73619.0     0.0
19    73621.0     0.0
21    73633.0     0.0
22    73638.0     0.0
23    73639.0     1.0
24    73640.0     0.0
26    73642.0     0.0
27    73647.0     0.0
29    73655.0     0.0
30    73656.0     0.0
31    73657.0     0.0
32    73659.0     1.0
33    73661.0     0.0
34    73663.0     0.0
...       ...     ...
3297  83630.0     0.0
3298  83633.0     0.0
3299  83637.0     0.0
3300  83638.0     0.0
3301  83642.0     0.0
3302  83646.0     0.0
3303  83648.0     0.0
3304  83655.0     1.0
3305  83658.0     0.0
3306  83666.0     0.0
3307  83671.0     0.0
3308  83673.0     0.0
3309  83676.0     1.0
3310  83677.0     0.0
3311  83678.0     0.0
3312  83679.0     0.0
3313  83683.0     0.0
3314  83692.0     0.0
3315  83694.0     0.0
3317  83699.0     0.0
3318  83702.0     0.0
3319  83707.0     0.0
3320  83708.0     1.0
3321  83711.0     0.0
3322  83712.0     0.0
3323  83713.0     0.0
3324  83714.0     0.0
3326  83718.0     0.0
3327  83723.0     1.0
3328  83727.0     0.0

[3172 rows x 2 columns]

In [8]:
plasma2

         SEQN  LBXGLU
0     83733.0     0.0
1     83734.0     0.0
2     83736.0     0.0
3     83737.0     0.0
4     83741.0     0.0
5     83743.0     0.0
6     83749.0     0.0
7     83750.0     0.0
8     83753.0     0.0
9     83754.0     1.0
10    83755.0     1.0
11    83757.0     1.0
12    83761.0     0.0
13    83764.0     1.0
14    83770.0     0.0
15    83773.0     0.0
16    83777.0     1.0
17    83778.0     0.0
18    83781.0     0.0
20    83787.0     0.0
21    83789.0     0.0
22    83790.0     1.0
23    83799.0     0.0
24    83801.0     0.0
25    83809.0     0.0
26    83813.0     0.0
27    83815.0     0.0
28    83816.0     0.0
29    83818.0     0.0
30    83820.0     0.0
...       ...     ...
3158  93577.0     0.0
3159  93582.0     0.0
3160  93589.0     0.0
3161  93590.0     0.0
3163  93592.0     0.0
3164  93593.0     0.0
3165  93595.0     0.0
3166  93598.0     0.0
3167  93600.0     0.0
3168  93602.0     0.0
3169  93607.0     1.0
3170  93608.0     0.0
3171  93611.0     0.0
3172  93612.0     0.0
3173  93619.0     0.0
3174  93624.0     0.0
3176  93639.0     0.0
3177  93643.0     0.0
3178  93645.0     0.0
3179  93649.0     0.0
3180  93655.0     0.0
3181  93656.0     1.0
3182  93663.0     0.0
3183  93664.0     0.0
3184  93677.0     0.0
3185  93682.0     0.0
3186  93687.0     0.0
3187  93689.0     0.0
3188  93695.0     0.0
3190  93697.0     0.0

[2972 rows x 2 columns]

In [9]:
plasma1.to_csv('diabetes_1314.csv',index=True)
plasma2.to_csv('diabetes_1516.csv',index=True)